version: '3.8'

services:

  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/server
    command: npm start
    working_dir: /usr/src/server
    ports:
      - '3001:3001'
